services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
